name = "pokemon_names"
version = "1.0.8"

description = "Get PokÃ©mon names"
licenses = ["MIT"]
repository = { type = "github", user = "emzinnia", repo = "gleam-pokemon" }

[targets]
erlang = true

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
